export const SETTINGS_MATERIAL_NAME_LIST_MAP = {
  THICKNESS: 'thickness',
  LENGTH: 'length',
  WIDTH: 'width',
  LENGTH_MM: 'lengthMM',
  SIZE: 'size',
  TYPE: 'type',
};

export const SETTINGS_MATERIAL_LABEL_LIST_MAP = {
  [SETTINGS_MATERIAL_NAME_LIST_MAP.THICKNESS]: 'Товщина металу, мм.',
  [SETTINGS_MATERIAL_NAME_LIST_MAP.LENGTH_MM]: 'Довжина, мм.',
  [SETTINGS_MATERIAL_NAME_LIST_MAP.LENGTH]: 'Довжина, м.',
  [SETTINGS_MATERIAL_NAME_LIST_MAP.WIDTH]: 'Ширина, мм.',
  [SETTINGS_MATERIAL_NAME_LIST_MAP.SIZE]: 'Розмір, мм.',
  [SETTINGS_MATERIAL_NAME_LIST_MAP.TYPE]: 'Тип',
};

export const SETTINGS_MATERIAL_UNIT_LIST_MAP = {
  [SETTINGS_MATERIAL_NAME_LIST_MAP.THICKNESS]: 'мм.',
  [SETTINGS_MATERIAL_NAME_LIST_MAP.LENGTH_MM]: 'мм.',
  [SETTINGS_MATERIAL_NAME_LIST_MAP.LENGTH]: 'м.',
  [SETTINGS_MATERIAL_NAME_LIST_MAP.WIDTH]: 'мм.',
  [SETTINGS_MATERIAL_NAME_LIST_MAP.SIZE]: 'мм.',
  [SETTINGS_MATERIAL_NAME_LIST_MAP.TYPE]: '',
};
